name: "Actions WorkFlow"

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -al
      - name: Checkout Action
        uses: actions/checkout@v2
      - name: List files after checkout
        run: |
          pwd
          ls -al
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John Doe
      - name: Log Gretting Time
        run: echo "${{ steps.greet.outputs.time }}"
