name: Matrix

on: [push]

jobs:
  node-version:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest]
        node-version: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: | 
          echo "os: ${{ matrix.os }} !!!!!!"
          node -v
