name: Shell commands

on: [push, pull_request]

jobs:
  # job name
  run-shell-commands:
    # virtual machine instance
    runs-on: ubuntu-latest
    steps:
      # for debbuging: https://docs.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging
      # enabling or adding these secrets with true value: ACTIONS_RUNNER_DEBUG & ACTIONS_STEP_DEBUG on settings repo
      - name: echo a string
        run: echo "hello world from github actions"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  # second job
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
        
