name: Shell commands

on: [push, pull_request]

jobs:
  # job name
  run-shell-commands:
    # virtual machine instance
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: eccho "hello world from github actions"
      - name: multiline script
        run: |
          node -v
          npm -v
  # for debbuging: https://docs.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging
  # enabling or adding these secrets with true value: ACTIONS_RUNNER_DEBUG & ACTIONS_STEP_DEBUG on settings repo
  