name: Shell commands

on: [push, pull_request]

jobs:
  # job name
  run-shell-commands:
    # virtual machine instance
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world from github actions"
      - name: multiline script
        run: |
          node -v
          npm -v